### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Mecanik** [cloudflare/pages-plugins#11]
Hello,

How exactly does one handle errors? It seems all plugin examples include return upon success. 

I for example do not understand this "syntax"... can you please explain?

Consider the hCaptcha plugin:

```
import hCaptchaPlugin from "@cloudflare/pages-plugin-hcaptcha";

export const onRequestPost: PagesFunction[] = [
  hcaptchaPlugin({
    secret: "0x0000000000000000000000000000000000000000",
    sitekey: "10000000-ffff-ffff-ffff-000000000001",
  }),
  (async ({ request }) => {
    // Request has been validated as coming from a human

    const formData = await request.formData()

    // Store user credentials

    return new Response("Successfully registered!")
  })

];
```

Where and how do I catch errors?

Thanks

**Comment by GregBrimble** [comment]
Hi!

Each Plugin handles its errors slightly differently. It's up to the author to decide whether to return a default response, or to throw an error or whatever. In the case of the hCaptcha Plugin, as stated in [the docs](https://developers.cloudflare.com/pages/platform/functions/plugins/hcaptcha/):

> `onError` is an optional function which takes the Pages Function context object and returns a Promise of a Response. By default, it will return a human-readable error Response.
> 
> `data.hCaptcha` will be populated in subsequent Pages Functions (including for the onError function) with [the hCaptcha response object](https://docs.hcaptcha.com/#verify-the-user-response-server-side).

So you can capture any errors and handle them as you wish by using this `onError` property:

```ts
import hCaptchaPlugin from "@cloudflare/pages-plugin-hcaptcha";

export const onRequestPost: PagesFunction[] = [
  hcaptchaPlugin({
    secret: "0x0000000000000000000000000000000000000000",
    sitekey: "10000000-ffff-ffff-ffff-000000000001",
    onError: async ({ data }) => {
      return new Response(`Denied access because of ${data.hCaptcha['error-codes']}.`)
    }
  }),
  (async ({ request }) => {
    // Request has been validated as coming from a human

    const formData = await request.formData()

    // Store user credentials

    return new Response("Successfully registered!")
  })
];
```

By default, the Plugin will return a 400 Response with a human-readable error message: https://github.com/cloudflare/pages-plugins/blob/main/packages/hcaptcha/functions/index.ts#L59-L71.
