### ISSUE TITLE
Cloudflare Access Pages Plugin always return 302

### ISSUE THREAD

**Issue by yuto343** [cloudflare/pages-plugins#13]
Cloudflare Access Pages Plugin always return 302 and redirected to `https://myteamname.cloudflareaccess.com/cdn-cgi/access/login/...` login page even if  have an authenticated JWT token.

## Problem
I researched problem and I found 2 errors below.
- There are no `typ` claim in JWT payload. 
- A `aud` claim is not string but array like `aud : [ "..." ]`.

## Dependencies
```
  "devDependencies": {
    "@cloudflare/workers-types": "^3.17.0",
    "@sveltejs/vite-plugin-svelte": "^1.0.2",
    "@tsconfig/svelte": "^3.0.0",
    "svelte": "^3.49.0",
    "svelte-check": "^2.8.1",
    "svelte-preprocess": "^4.10.7",
    "tslib": "^2.4.0",
    "typescript": "^4.6.4",
    "vite": "^3.1.0"
  },
  "dependencies": {
    "@cloudflare/pages-plugin-cloudflare-access": "^1.0.1"
  }
```

**Comment by GregBrimble** [comment]
I'm unable to reproduce this. Can you please include an example setup which results in the @cloudflare/pages-plugin-cloudflare-access Pages Plugin always returning 302s?
