### ISSUE TITLE
Cloudflare Static Form only returns 200 status OK codes

### ISSUE THREAD

**Issue by yhorian** [cloudflare/pages-plugins#21]
Here's how to replicate the bug:

1. [Go to the docs](https://developers.cloudflare.com/pages/platform/functions/plugins/static-forms/), copy the commands and code.
2. Create another function designed to redirect by adding /functions/test.js:

```
// functions/test.js
export function onRequest(context) {
            return Response.redirect("https://example.com/about/", 302)
          }
```
3. Deploy to Cloudflare pages. Check the /test/ route with curl.

You'll get a blank body and it has a status 200 OK but a valid location header for /about/. The response object is created successfully but transformed by the plugin to have a 200 code instead.

This is fixed by removing the static forms plugin. MailChannels uses static forms, and shares this bug. Installing either breaks redirects.

Because it's deployed as middleware, any attempt to change codes with functions across the site breaks. The solution has been to strip out the transform added when the function is compiled. It's applied to the handler's response to check for status codes:

```
var cloneResponse = (response) => new Response(
  [101, 204, 205, 304].includes(response.status) ? null : response.body,
  response
);
```
Once removed, everything works as expected. I haven't tested using the Response.clone() instead because I don't see why a custom handler function needs this kind of check on it.

**Comment by GregBrimble** [comment]
This should now be fixed! Let me know if the issue persists after upgrading to @cloudflare/pages-plugin-static-forms@1.0.1.
