### ISSUE TITLE
Sentry plugin (all middleware?) breaks cached responses

### ISSUE THREAD

**Issue by IanVS** [cloudflare/pages-plugins#23]
After adding the sentry plugin as middleware to my site, I started to experience very poor behavior:

- When loading or reloading the page, there is a chance that the html response is given a status of 200 but no payload.  I would expect a 304 instead, if the browser should use its cached version.
- Sometimes the html will load, but not the CSS.  It seems totally random.
- When hard-refreshing pages, they load fine

For an example of this on a simple page, see; https://bb9fafc1.www-defined.pages.dev/.  Refresh several times and you will see different behaviors.

Removing the sentry plugin resolves the issue.  This is my plugin:

```ts
// functions/_middleware.ts

import sentryPlugin from "@cloudflare/pages-plugin-sentry";

export const onRequest: PagesFunction<{
  SENTRY_DSN: string;
  SENTRY_ENVIRONMENT: "production" | "deploy-preview";
}> = (context) => {
  return sentryPlugin({
    dsn: context.env.SENTRY_DSN,
    environment: context.env.SENTRY_ENVIRONMENT,
  })(context);
};
```

When watching the function log stream, refreshing the page will show a successful GET to /site.manifest sometimes, but not always.  If the page comes up blank, I don't see a log.

Other users in Discord have also reported similar issues when using Cloudflare Access middleware.  Is it possible that middleware in general is the cause of this?

**Comment by HeyITGuyFixIt** [comment]
I replicated this here: https://gitlab.com/ChristianSirolli/cf-pages, which is hosted at https://cf-pages-8zu.pages.dev/. It uses `@cloudflare/pages-plugin-cloudflare-access`, and only started this behavior after setting up this middleware.

**Comment by IanVS** [comment]
I was told in Discord there should be a fix for this coming soon.  🤞

**Comment by GregBrimble** [comment]
This should now be fixed! Let me know if the issue persists after upgrading to @cloudflare/pages-plugin-sentry@1.1.1.

**Comment by IanVS** [comment]
Confirmed it's working, thanks!
