### ISSUE TITLE
npm ERR! 404  '@cloudflare/pages-plugin-headers@*' is not in this registry.

### ISSUE THREAD

**Issue by dikaio** [cloudflare/pages-plugins#3]
Receiving the following error on install via `npm install --save @cloudflare/pages-plugin-headers`

```
npm ERR! 404  '@cloudflare/pages-plugin-headers@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*/.npm/_logs/2022-05-18T02_54_45_937Z-debug-0.log
```

**Comment by GregBrimble** [comment]
Hi @dikaio ,

We've intentionally not published this Plugin. It was mostly used just for testing, and more functionality is possible with [the `_headers` file](https://developers.cloudflare.com/pages/platform/headers/).
