### ISSUE TITLE
Is it possible to access env in cloudflare access plugin

### ISSUE THREAD

**Issue by andrewheberle** [cloudflare/pages-plugins#31]
I'm attempting to access env vars in the Cloudflare Access Pages Plugin and cannot work out how to get this to work.

My use case is the very simple option of having an environment var for the "aud" value set in production and then differently in development builds.

Is this possible and is there any examples I can refer to for this?

**Comment by GregBrimble** [comment]
You should be able to do something like the second example here: https://developers.cloudflare.com/pages/platform/functions/plugins/sentry/#usage

```ts
export const onRequest = (context) => {
  return cloudflareAccessPlugin({ 
    domain: "https://test.cloudflareaccess.com",
    aud: context.env.MY_AUD_ENV_VAR
  })(context)
}
