### ISSUE TITLE
fix(static-forms): input type="hidden" is not appended

### ISSUE THREAD

**Issue by dargmuesli** [cloudflare/pages-plugins#34]
Somehow `form.append` does not seem to work:
https://github.com/cloudflare/pages-plugins/blob/c9bdd1e8a10ad276958c399111a1e5293574af4f/packages/static-forms/functions/_middleware.ts#L37

As you can see under https://aa4ad788.jonas-thelemann.pages.dev/contact the form receives a `method="POST"` but no `input type="hidden"` is appended. This breaks the mailchannels plugin's email sending.

**Comment by GregBrimble** [comment]
In that example you linked, I _can_ see the hidden input. Can you confirm if you're still seeing this issue?

**Comment by dargmuesli** [comment]
Ah, so it appears to only be part of the server's response but removed on the client side?
