### ISSUE TITLE
Mailchannels: support for attachments

### ISSUE THREAD

**Issue by ibobo** [cloudflare/pages-plugins#38]
Hi, I had to make a "Work with us" form, which included a resume upload field, that obviously should be sent by mail. Looking in the Mailchannels API documentation, the plugin documentation or source code I could not find any mention about attachments. From the Mailchannels API docs it seems to be supported, but I couldn't find any example.

The only workaround I found was to use a link with a Data URI and encode the attachment there, but it doesn't work in some clients (ie. Gmail strips the link completely).

In any case, sending attachments should be available, or, if unsupported at all, that should be mentioned in the documentation.

**Comment by GregBrimble** [comment]
Thanks for filing this issue. This plugin has now been deprecated on account of MailChannels' sunsetting of their free email sending API (#63), so I'm going to close out this issue.
