### ISSUE TITLE
Static Forms and Mailchannels Plugin breaking other forms

### ISSUE THREAD

**Issue by beartrack** [cloudflare/pages-plugins#39]
While the documentation says these plugins "intercept all form submissions made which have the data-static-form-name attribute set", they were breaking the search function and other forms on my site which do not have that attribute set. I was able to restore the expected behavior by replacing: 

`return new HTMLRewriter().on("form", {`

with:

`return new HTMLRewriter().on('[data-static-form-name]', {`

**Comment by GregBrimble** [comment]
Fixed by #41
